name = "Simwise"
uuid = "dcfbcffb-3b0a-4852-b6b9-f66716b7c1fc"
version = "0.1.0"
authors = ["Colin Skinner <colinaskinner@gmail.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SatelliteDynamics = "0e7c1a32-1b9f-5532-88a4-e668712d6a4c"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SatelliteToolboxGeomagneticField = "9fc549ba-b5d7-49a2-b268-8171e5fb6e89"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
SatelliteToolbox = "1"
Statistics = "1.11.1"
julia = "1.10"

[compat]
DataStructures = "0.19.1"
Printf = "1.11.0"
SatelliteToolbox = "1"
julia = "1.10"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test"]
